### ISSUE TITLE
Bug: Pagination out of bounds

### ISSUE THREAD

**Issue by mster** [mster/fireferret#2]
Example Error
```sh
{"level":50,"time":1596248117731,"pid":16023,"hostname":"ubuntu","reqId":11,"req":{"method":"GET","url":"/api/plants?q={%22plantName%22:%22Derek%22}&pagination={%22page%22:1000,%22size%22:50}","hostname":"127.0.0.1:3371","remoteAddress":"127.0.0.1","remotePort":40798},"res":{"statusCode":500},"err":{"type":"FFError","message":"Keys are required for multihgetall","stack":"InvalidArguments: Keys are required for multihgetall\n    at RedisClient.multihgetall (/home/m/code/planterdocs/fetch-api/node_modules/fireferret/lib/redis.js:111:13)\n    at cacheHit (/home/m/code/planterdocs/fetch-api/node_modules/fireferret/lib/client.js:86:39)\n    at FireFerret.fetch (/home/m/code/planterdocs/fetch-api/node_modules/fireferret/lib/client.js:125:12)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.module.exports.getPlants (/home/m/code/planterdocs/fetch-api/src/handlers/plants.js:32:20)","name":"InvalidArguments"},"msg":"Keys are required for multihgetall"}
```

**Comment by mster** [comment]
closed in https://github.com/mster/fireferret/commit/8b47ace00eb9872954e91fb0ca47f32ea38127cd
