### ISSUE TITLE
Bug: Pagination deconstruction failure

### ISSUE THREAD

**Issue by mster** [mster/fireferret#3]
Example Error:
```js
{"level":50,"time":1596248052800,"pid":16023,"hostname":"ubuntu","reqId":7,"req":{"method":"GET","url":"/api/plants?q={plantName:%22Derek%22}&pagination={%22page%22:1,%22size%22:50}","hostname":"127.0.0.1:3371","remoteAddress":"127.0.0.1","remotePort":40790},"res":{"statusCode":500},"err":{"type":"SyntaxError","message":"Unexpected token p in JSON at position 1","stack":"SyntaxError: Unexpected token p in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at Object.module.exports.getPlants (/home/m/code/planterdocs/fetch-api/src/handlers/plants.js:17:18)\n    at preHandlerCallback (/home/m/code/planterdocs/fetch-api/node_modules/fastify/lib/handleRequest.js:120:28)\n    at preValidationCallback (/home/m/code/planterdocs/fetch-api/node_modules/fastify/lib/handleRequest.js:103:5)\n    at handler (/home/m/code/planterdocs/fetch-api/node_modules/fastify/lib/handleRequest.js:69:5)\n    at handleRequest (/home/m/code/planterdocs/fetch-api/node_modules/fastify/lib/handleRequest.js:18:5)\n    at runPreParsing (/home/m/code/planterdocs/fetch-api/node_modules/fastify/lib/route.js:358:5)\n    at Object.routeHandler [as handler] (/home/m/code/planterdocs/fetch-api/node_modules/fastify/lib/route.js:334:7)\n    at Router.lookup (/home/m/code/planterdocs/fetch-api/node_modules/find-my-way/index.js:351:14)\n    at Server.emit (events.js:311:20)"},"msg":"Unexpected token p in JSON at position 1"}
```

**Comment by mster** [comment]
closed in https://github.com/mster/fireferret/commit/8b47ace00eb9872954e91fb0ca47f32ea38127cd
