### ISSUE TITLE
Bug: empty query with empty options failure

### ISSUE THREAD

**Issue by mster** [mster/fireferret#4]
Example Error:
```
Cannot destructure property 'page' of 'options.pagination' as it is undefined.
```

**Comment by mster** [comment]
related to #3

**Comment by mster** [comment]
More context:
```js
{"level":50,"time":1596248368615,"pid":16023,"hostname":"ubuntu","reqId":12,"req":{"method":"GET","url":"/api/plants","hostname":"127.0.0.1:3371","remoteAddress":"127.0.0.1","remotePort":40906},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Cannot destructure property 'page' of 'options.pagination' as it is undefined.","stack":"TypeError: Cannot destructure property 'page' of 'options.pagination' as it is undefined.\n    at cacheHit (/home/m/code/planterdocs/fetch-api/node_modules/fireferret/lib/client.js:68:13)\n    at FireFerret.fetch (/home/m/code/planterdocs/fetch-api/node_modules/fireferret/lib/client.js:125:12)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.module.exports.getPlants (/home/m/code/planterdocs/fetch-api/src/handlers/plants.js:27:20)"},"msg":"Cannot destructure property 'page' of 'options.pagination' as it is undefined."}
{"level":30,"time":1596248368616,"pid":16023,"hostname":"ubuntu","reqId":12,"res":{"statusCode":500},"responseTime":28.8254819996655,"msg":"request completed"}
```

**Comment by mster** [comment]
bad query opts
